require('dotenv').config()
const express = require('express')
const mongoose = require('./config/db')
const authRoutes = require('./routes/auth')
const subscriptionRoutes = require('./routes/subscription')
const contentRoutes = require('./routes/content')
const app = express()
app.use(express.json())
app.use('/auth', authRoutes)
app.use('/subscription', subscriptionRoutes)
app.use('/content', contentRoutes)
app.listen(process.env.PORT || 3000)
